export const fallbackCategories = [
  {
    _id: "fallback-apparel",
    name: "Apparel and Accessories",
    slug: "apparel-and-accessories",
    image: "/assets/categories/apparel.webp",
    description: "Customized corporate apparel, uniforms, caps, shirts, ties, aprons, and winter wear for teams and events.",
    subcategories: [],
  },
  {
    _id: "fallback-eco",
    name: "Eco Products",
    slug: "eco-products",
    image: "/assets/categories/ecoproducts.webp",
    description: "Eco-conscious cork, bamboo, and sustainable gifting products for green corporate campaigns.",
    subcategories: [],
  },
  {
    _id: "fallback-tech",
    name: "Technology Accessories",
    slug: "technology-accessories",
    image: "/assets/categories/technology.webp",
    description: "Branded tech gifts including wireless chargers, power banks, computer accessories, and mousepads.",
    subcategories: [],
  },
  {
    _id: "fallback-drinkware",
    name: "Drink Ware",
    slug: "drink-ware",
    image: "/assets/categories/drinkware.webp",
    description: "Custom bottles, bamboo bottles, ceramic mugs, and coffee mugs for daily brand visibility.",
    subcategories: [],
  },
  {
    _id: "fallback-bags",
    name: "Bags and Travel",
    slug: "bags-and-travel",
    image: "/assets/categories/bags.webp",
    description: "Backpacks, foldable bags, duffle bags, and tote bags for events, travel kits, and promotions.",
    subcategories: [],
  },
  {
    _id: "fallback-office",
    name: "Office and Writing",
    slug: "office-and-writing",
    image: "/assets/categories/officewriting.webp",
    description: "Branded notebooks, diaries, pens, folders, lanyards, and office essentials.",
    subcategories: [],
  },
  {
    _id: "fallback-collection",
    name: "Collection",
    slug: "collection",
    image: "/assets/categories/collections.webp",
    description: "Welcome kits, keychains, clocks, and curated promotional gift collections.",
    subcategories: [],
  },
  {
    _id: "fallback-trophy",
    name: "Trophy and Momento",
    slug: "trophy-and-momento",
    image: "/assets/categories/trophy.webp",
    description: "Custom trophies and mementos for recognition, awards, milestones, and events.",
    subcategories: [],
  },
];

export const fallbackSubcategories = [
  ["Promotional T-Shirt Manufacturers in Delhi", "polo-t-shirts", "fallback-apparel", "Apparel and Accessories", "/assets/subcategories/polotshirt.webp"],
  ["Promotional Round Neck T-Shirts", "round-neck-t-shirts", "fallback-apparel", "Apparel and Accessories", "/assets/subcategories/round.webp"],
  ["Custom Cap Manufacturer in Delhi NCR", "caps", "fallback-apparel", "Apparel and Accessories", "/assets/subcategories/cap.webp"],
  ["Customized Formal Shirt in Delhi", "corporate-shirts", "fallback-apparel", "Apparel and Accessories", "/assets/subcategories/corporateshirt.webp"],
  ["Promotional Apron in Delhi", "aprons", "fallback-apparel", "Apparel and Accessories", "/assets/subcategories/apron.webp"],
  ["Cork Corporate Gifting Combo", "cork-corporate-gifting-combo", "fallback-eco", "Eco Products", "/assets/subcategories/combo.webp"],
  ["Cork Coaster", "cork-coaster", "fallback-eco", "Eco Products", "/assets/subcategories/coaster.webp"],
  ["Cork Desk Top Accessories", "cork-desk-top-accessories", "fallback-eco", "Eco Products", "/assets/subcategories/desk.webp"],
  ["Wireless Charging", "wireless-charging", "fallback-tech", "Technology Accessories", "/assets/products/wirelesschargers/1.webp"],
  ["Power Banks", "power-banks", "fallback-tech", "Technology Accessories", "/assets/products/powerbanks/1.webp"],
  ["Sipper Bottles", "sipper", "fallback-drinkware", "Drink Ware", "/assets/products/sipperbottles/1.webp"],
  ["Coffee Mug", "coffee-mug", "fallback-drinkware", "Drink Ware", "/assets/products/coffeemugs/1.webp"],
  ["Backpacks", "backpacks", "fallback-bags", "Bags and Travel", "/assets/products/backpacks/1.webp"],
  ["Duffle Bags", "duffle-bags", "fallback-bags", "Bags and Travel", "/assets/products/dufflebags/1.webp"],
  ["Notebook & Diary Sets", "notebooks-and-diary-sets", "fallback-office", "Office and Writing", "/assets/products/notebooks/1.webp"],
  ["Pen & Writing Set", "pen-and-writing-set", "fallback-office", "Office and Writing", "/assets/products/pens/1.webp"],
  ["Welcome Kits", "welcome-kits", "fallback-collection", "Collection", "/assets/products/welcomekits/1.webp"],
  ["Keychains", "keychains", "fallback-collection", "Collection", "/assets/products/keychains/1.webp"],
].map(([name, slug, category, categoryName, image]) => ({
  _id: `fallback-sub-${slug}`,
  name,
  slug,
  category,
  categoryName,
  image,
  description: `High-quality ${name} designed for corporate branding, promotional events, employee gifting, and bulk orders across Delhi NCR and India.`,
}));

export const fallbackProducts = [
  ["Premium Polo T-Shirt", "premium-polo-t-shirt", "fallback-apparel", "fallback-sub-polo-t-shirts", "Apparel and Accessories", "Promotional T-Shirt Manufacturers in Delhi", "/assets/products/polo/black (1).webp", 399],
  ["Classic Round Neck T-Shirt", "classic-round-neck-t-shirt", "fallback-apparel", "fallback-sub-round-neck-t-shirts", "Apparel and Accessories", "Promotional Round Neck T-Shirts", "/assets/products/roundneck/black (1).webp", 249],
  ["Custom Corporate Cap", "custom-corporate-cap", "fallback-apparel", "fallback-sub-caps", "Apparel and Accessories", "Custom Cap Manufacturer in Delhi NCR", "/assets/products/caps/black (1).webp", 149],
  ["Corporate Cork Gift Combo", "corporate-cork-gift-combo", "fallback-eco", "fallback-sub-cork-corporate-gifting-combo", "Eco Products", "Cork Corporate Gifting Combo", "/assets/products/cork/box (1).webp", 799],
  ["Wireless Charger", "wireless-charger", "fallback-tech", "fallback-sub-wireless-charging", "Technology Accessories", "Wireless Charging", "/assets/products/wirelesschargers/1.webp", 699],
  ["Branded Power Bank", "branded-power-bank", "fallback-tech", "fallback-sub-power-banks", "Technology Accessories", "Power Banks", "/assets/products/powerbanks/1.webp", 999],
  ["Premium Corporate Gift Mug", "premium-corporate-gift-mug", "fallback-drinkware", "fallback-sub-coffee-mug", "Drink Ware", "Coffee Mug", "/assets/products/coffeemugs/1.webp", 199],
  ["Employee Welcome Kit", "employee-welcome-kit", "fallback-collection", "fallback-sub-welcome-kits", "Collection", "Welcome Kits", "/assets/products/welcomekits/1.webp", 1299],
].map(([name, slug, category, subcategory, categoryName, subcategoryName, image, price]) => ({
  _id: `fallback-product-${slug}`,
  name,
  slug,
  category,
  subcategory,
  categoryName,
  subcategoryName,
  price,
  salePrice: null,
  stock: 100,
  sku: slug.toUpperCase().replaceAll("-", "-"),
  images: [{ url: image, altText: name }],
  description: {
    short: `Buy ${name} with custom branding and logo printing for corporate gifting, employee kits, and promotional campaigns.`,
    long: `${name} is suitable for bulk corporate orders, event giveaways, onboarding kits, and brand merchandise.`,
  },
  tags: ["corporate gifts", "custom branding", "bulk order"],
  attributes: { color: ["Black", "White"], size: ["Standard"], material: "Premium finish" },
}));
